### ISSUE TITLE
Unable to install with npm on windows

### ISSUE THREAD

**Issue by Daniel-Amadeus** [baluubas/voice-command#2]
When I try to install it on Windows I get this error:

```
> voice-command@0.0.4 install C:\Users\dajg1\Documents\HPI\HCI\masterproject\dualpantoframework\node_modules\voice-command
> node ./build/build-release.js

C:\Users\dajg1\Documents\HPI\HCI\masterproject\dualpantoframework\node_modules\voice-command\build\build-release.js:12
        throw new Exception('Platform ' + platform + ' is not supported yet.');
        ^

ReferenceError: Exception is not defined
    at Object.<anonymous> (C:\Users\...\Documents\HPI\HCI\masterproject\dualpantoframework\node_modules\voice-command\build\build-release.js:12:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! voice-command@0.0.4 install: `node ./build/build-release.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the voice-command@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Roaming\npm-cache\_logs\2018-04-16T13_19_21_016Z-debug.log
```

**Comment by baluubas** [comment]
Hi, 

This was a one off thing for me so it's not something I work on actively. Feel free to fork and fix any issues you might have.

From what I can tell there is two parts to you problem. First, there is a typo-bug in the build-release.js script (it should be `throw new Error('Platform ' + platform + ' is not supported yet.');` ). Second, it seems your platform is not supported. :)
